### ISSUE TITLE
An  Example for Single Page App?

### ISSUE THREAD

**Issue by sclee15** [davidmarne/wui_builder#17]
I like the motivation of wui_builder.

I really love it.

I hope that i can see an example of single page app with wui_builder

**Comment by davidmarne** [comment]
Sure, I'ld love to provide better examples for spas. I am curious what exactly you are looking for in a spa example.

Routing?
State management (via built_redux, redux.dart, or w_flux)?
Server/Firebase integration?
All of the above?

**Comment by sclee15** [comment]
I personally prefer to use built_value for the state management.
But the routing and event from outside (ex: the button click event from outside of the wui_components) are my missing puzzle for now.
I tested wui_builder as an AngularDart (or React) replacement.
I think it is good for the best of both world.

**Comment by davidmarne** [comment]
Cool!

Well as I said, I'ld love to provide a more in depth example. However, it might not be for a little bit because I'm going to be pretty busy the next couple weeks/weekends.

Subscribing to events from outside a component can be done by passing a stream for those events to a component and subscribing to the stream in componentDidMount (and then cancelling your stream subscription in componentWillUnmount).

```dart
class MyComponent extends PComponent<Stream<int>, int> {
  StreamSubscription streamSubscription;

  MyComponent(Stream props) : super(props);
 
  @override
  void componentDidMount() {
    // set the component's state when the stream fires.
    streamSubscription = props.listen((int streamValue) => setState(streamValue));
  }

  @override
  void componentWillUnmount() {
    streamSubscription.cancel();
  }
  ...
}
```

In the meantime I would also suggest taking a look at the wui_builder example in [built_redux_todos](https://github.com/davidmarne/built_redux_todos). It is a slightly more complex example that uses [built_redux](https://github.com/davidmarne/built_redux) to contain the application state in a redux store. This gives you a state container that can live outside your components, and contain common state many different components may want access to.

I realize the documentation in that repo is a bit lacking, but essentially what it is doing is [subscribing to the store](https://github.com/davidmarne/built_redux_todos/blob/master/examples/wui_builder/lib/src/app.dart#L27) in the top level component, Container, which then passes the pieces of state the children components need access to via props. You'll also notice actions are passed to the children components, which are used to update state in the redux store from the children components.

**Comment by sclee15** [comment]
Thanks it helped me alot
