### ISSUE TITLE
What is the role of inner prop?

### ISSUE THREAD

**Issue by sclee15** [davidmarne/wui_builder#7]
I think in todo app example
It passes just null but I think this is more than just null..

Thank you.

**Comment by davidmarne** [comment]
So that example uses the functional library, which is a library of high order components (HOCs) for building components functionally rather than by using classes. HOCs are components that wrap other components to provide additionally functionality.

With that said,  HOCs are a fairly advanced concept, and the standard way to write components is by writing classes that extends the Component class. I just added a similar todos example with class based components [here](https://github.com/davidmarne/wui_builder/tree/master/example/todos_class_components)

However, if you are interested in writing functional components with HOCs, I can elaborate more on what is going on:

The [container](https://github.com/davidmarne/wui_builder/blob/master/example/todos_functional_components/lib/src/container.dart#L48) function in that example takes no props. However, the functional component passed to the withState HOC ( [_container](https://github.com/davidmarne/wui_builder/blob/master/example/todos_functional_components/lib/src/container.dart#L52)) takes ContainerProps. In this example the inner props are of type ContainerProps and the outter props are of type Null.

The withState HOC is essentially setting up some state and passing it down to [_container](https://github.com/davidmarne/wui_builder/blob/master/example/todos_functional_components/lib/src/container.dart#L52). I would read the more into HOC's & [recompose](https://github.com/acdlite/recompose) for reactjs if you are interested.

**Comment by davidmarne** [comment]
I will have to try to and improve the comments in those examples. I'm sorry for the poor documentation.

**Comment by sclee15** [comment]
Thank you.
I really like the new class based way.
